services:
  app:
    build:
      context: .
      dockerfile: .docker/js-app/prod/Dockerfile
    container_name: quokka_app
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - fastify_network
    restart:
        unless-stopped
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
  db:
    image: postgres:latest
    container_name: quokka_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastify_network
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  fastify_network:
    driver: bridge

volumes:
  postgres_data:
